services:
    postgres:
        image: postgres:15.3-alpine3.18
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
            timeout: 45s
            interval: 10s
            retries: 3
        restart: unless-stopped
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - postgres-app-data:/var/lib/postgresql/data
            - ./postgres_init/:/docker-entrypoint-initdb.d/
        networks:
            - postgres-bridge

    pgadmin:
        build:
            context: pgadmin
            dockerfile: Dockerfile
        env_file: .env
        environment:
            PGADMIN_DEFAULT_EMAIL: 'pgadmin4@example.com'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        healthcheck:
            test: [ "CMD", "wget", "-O", "-", "http://localhost:80/misc/ping" ]
            interval: 10s
            timeout: 10s
            retries: 5
        ports:
            - "5050:80"
        networks:
            - postgres-bridge
        restart: unless-stopped
        depends_on:
            - postgres

networks:
    postgres-bridge:

volumes:
    postgres-app-data:
    pgadmin-data:
