services:
    postgres:
        image: postgres:14.6-alpine
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
            timeout: 45s
            interval: 10s
            retries: 3
        restart: unless-stopped
        environment:
            TZ: UTC
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            APP_DB_USER: app
            APP_DB_PASS: password
            APP_DB_NAME: my_app
        ports:
            - "5432:5432"
        volumes:
            - postgres-app-data:/var/lib/postgresql/data
            - ./postgres_init/:/docker-entrypoint-initdb.d/

volumes:
    postgres-app-data:
